### ISSUE TITLE
Clarify "commit often, as most as you can, perfection later"

### ISSUE THREAD

**Issue by peterjc** [ypriverol/github-paper#101]
To me this "rule" does not flow as natural English, and the meaning is unclear. I'm unsure if the middle part means as often as possible, or as much as possible (i.e. all changed files)

**Comment by sje30** [comment]
"Commit early,commit often, and commit in a repository from which we
    can easily roll-back your mistakes" (AJR, 4Jan05).

The above quote is from the email signature of Tony Rossin (@blindglobe  on github).  I think that sums it up nicely and shows these ideas have been around for a long time.  Tony has been a long-term developer of Emacs Speaks Statistics.

**Comment by peterjc** [comment]
Tony's version make more sense - although the final clause might be a bit too complicated for an introductory paper.

**Comment by ypriverol** [comment]
@sje30 How can we cite this quote?

**Comment by blindglobe** [comment]
It sums up my development philosophy in a nutshell.  Especially since
encouraging experiments (and acknowledgement of future mistakes as being
good things) is a very core trait of making people perform (in software
development and life) above their own expectations.

**Comment by blindglobe** [comment]
Heck.  Just use it.  Even if you cannot cite it :)

**Comment by lgatto** [comment]
What about

> Following Tony Rossin's advice "commit early, commit often, and commit in a repository from which we can easily roll-back your mistakes", one can keep track of the development in small incremental changes. This development methodology encourages experiments (and acknowledges future mistakes as being good things), enabling to easily roll back without compromising the whole project.

**Comment by sje30** [comment]
A quick dig around on the mailing list found this being used by Tony on 12 Jan 2005.  Probably not the first use, but early enough!

https://stat.ethz.ch/pipermail/r-sig-qa/2005-January/000007.html

**Comment by ypriverol** [comment]
@lgatto I don't like the idea of adding a url of a mailing list to the page.

**Comment by sje30** [comment]
https://mailman.stat.ethz.ch/pipermail/r-help/2005-January/063587.html is 5th January.

**Comment by sje30** [comment]
@ypriverol Agree -- no need to add the URL, its just an email sig, and you can point to this issue if you want to document the origin of the quote.  Much more useful than link to the mailing list archive.

**Comment by lgatto** [comment]
> @lgatto I don't like the idea of adding a url of a mailing list to the manuscript.

There is no url in my suggestion.

**Comment by blindglobe** [comment]
+1

**Comment by ypriverol** [comment]
Ok I will included it.

**Comment by sje30** [comment]
laurent, your change looks fine, although please note Tony's surname is Rossini (my mistake earlier).  how about also saying 
    Following Tony Rossini's advice in 2005 to "commit ...

**Comment by lgatto** [comment]
My mistake re surname. Good idea to add the date.

**Comment by ypriverol** [comment]
@sje30 @lgatto is already added .. pull-request ready for you @lgatto https://github.com/ypriverol/github-paper/pull/116

**Comment by lgatto** [comment]
Great!

**Comment by ypriverol** [comment]
I ask for a citation but it apparently is not available for me is wear the current way if we don't have the citation
