### ISSUE TITLE
... often coined as a social coding platform ...

### ISSUE THREAD

**Issue by peterjc** [ypriverol/github-paper#102]
*It [GitHub] provides developers and researchers with a dynamic and collaborative environment, often coined as social coding platform, with the ability to review, comment and discuss code*

I presume you mean coined as a verb for inventing terminology, but it does not flow nicely.

How about *..., often referred to as a social coding platform, ...* or *..., often regarded as a social coding platform, ...* or *..., often viewed as a social coding platform, ...*.

**Comment by prvst** [comment]
_(...) often referred (...) _ sounds better to me

**Comment by ypriverol** [comment]
I replaced coined by viewed please @prvst accept the pull-request https://github.com/ypriverol/github-paper/pull/108

**Comment by ypriverol** [comment]
+1 done
