### ISSUE TITLE
Introduction, git not developed by Linus anymore

### ISSUE THREAD

**Issue by kblin** [ypriverol/github-paper#106]
In your introduction, you state that git was created and I'd developed by Linus Torvalds. Linus is not heading the git project anymore, it's now run by Junio Hamano.

**Comment by ypriverol** [comment]
Thanks @kblin for the comment. I will make a correction to the introduction.

**Comment by ypriverol** [comment]
Old version:
> GitHub relies, at its core, on the well-known and open source version
control system git, designed and developed by Linus Torvalds for the
development of the Linux kernel.

New version:

> GitHub relies, at its core, on the well-known and open source version
control system git, designed by Linus Torvalds for the development of the Linux kernel. Nowadays, git is developed and maintained by the git community (https://github.com/git).
