### ISSUE TITLE
"README.md" is the second most important file in a repo

### ISSUE THREAD

**Issue by sje30** [ypriverol/github-paper#110]
The subject line comes from a talk given by Arfon Smith (github).  I think this is important to stress.  (That along with the first most important -- the LICEN[CS]E file.

**Comment by lgatto** [comment]
I think this is an important point that we should address. I will add this, either as a rule (we had discussion about merging some), or as a box. Thanks for this suggestion.

**Comment by lgatto** [comment]
Here is @arfon's [CW14 talk](https://dl.dropboxusercontent.com/u/150135718/CW14/Arfon-Smith-27-03-14-CW14.pdf):
1. License
2. README
3. script/bootstrap

We definitely need to add this to the paper.

**Comment by sje30** [comment]
Please do!

I think item 3 though seems quite specific to that repo.  My vote for the generic number 3 important file would be the Makefile.

**Comment by lgatto** [comment]
I would also add a `CITATION` file, or, alternatively, explain how to cite in the `README` file.

**Comment by alex-konovalov** [comment]
@lgatto :+1: You beat me with `CITATION` by 5 seconds :) It fits nicely under rule 8.

Some projects also have `CONTRIBUTING` to split user and developer parts of README, but I'm afraid that already increases a list of files too much and may be omitted.

On a related note - would you like to explain that README.md and not README because GitHub will render markdown better, and also tell what markdown is (link to https://help.github.com/articles/about-writing-and-formatting-on-github/) ?

**Comment by alex-konovalov** [comment]
P.S. since LICENSE.md is already mentioned here: one could add "Further advice could be found, for example, at http://choosealicense.com/"  to the last paragraph of Rule 8. This is quite useful resource helping to choose a license if you're not a lawyer :)

**Comment by lgatto** [comment]
I have added a *Box 3* in my local fork https://github.com/lgatto/github-paper. Comments and suggestion welcome. 

@sje30 I haven't mention a `Makefile` in the end, as I thought this would diverge a bit too much from the main topic of the paper. We could possibly mention `Makefile`s in Rule 6 about automation although, again, we might err toward the general best practice away from `git` and GitHub.

**Comment by sje30** [comment]
OK re omitting make.

On 31 March 2016 02:03:46 BST, Laurent Gatto <notifications@github.com> wrote:
>I have added a *Box 3* in my local fork
>https://github.com/lgatto/github-paper. Comments and suggestion
>welcome. 
>
>@sje30 I haven't mention a `Makefile` in the end, as I thought this
>would diverge a bit too much from the main topic of the paper. We could
>possibly mention `Makefile`s in Rule 6 about automation although,
>again, we might err toward the general best practice away from `git`
>and GitHub.  
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/ypriverol/github-paper/issues/110#issuecomment-203700834

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by lgatto** [comment]
@sje30 are you happy with Box 3?

**Comment by ypriverol** [comment]
@lgatto I like both the current version. I guess we can close this issue.

**Comment by sje30** [comment]
I like it, but two minor suggestions:

1. write "three" not "3".

2. I thought Arfon said LICENCE was most important, followed by README, and I think that you should list them in that order too.

**Comment by ypriverol** [comment]
@sje30 done
