### ISSUE TITLE
When to go public with your repo?

### ISSUE THREAD

**Issue by sje30** [ypriverol/github-paper#111]
but thorny issue of when to make repo public needs addressing in
my view.  Here are some options:

1. make repo public from day 1.  Risk of getting scooped highest, but also highest potential gain from others joining in.  (http://opensourcebrain.org follows this model).

2. make repo private from day 1, then when to make public?

2a: at time of submission to journal.  this is what I do NORMALLY  if everyone agrees.  It
then means reviewers can see/review code.

2b: at time of acceptance of paper.

2c: at time of publication.

2d: never.  (!!!)

Code review by reviewers is becoming more important (e.g. Nature methods
2015 paper).  So making code available to reviewers is important, and
needs to be done anonymously.  github has no way of anonymously granting
access to a private repo. I think https://cos.io have a better solution here.

**Comment by rmflight** [comment]
If repo is public from day 1, then how can you actually get scooped? Have public proof that you were working on this first, IMHO.

**Comment by sje30** [comment]
Yes you have proof.  But that doesn't stop others from being able to see your ideas, and publish their paper first.

**Comment by ypriverol** [comment]
@sje30 @rmflight probably is not the aim of the manuscript to say when get public rather than give or suggest the options.

**Comment by lgatto** [comment]
I think this is actually an good point to address in the manuscript - we have the opportunity to make a clear statement about openness. This could be formulated in a `Box` on its own. We don't need to go into details and controversies about scooping, credit and precedence, but making it explicit that there are different paths to collaborative development (open from the beginning; closed, then open at some point; or, well closed), and than closed as in not public can still be a great way to collaborate privately. This is a great way to bring people that are not a wary of full openness to collaborative development, and, hopefully, invite them to be more open. Finally, there are sometimes reasons to remain private, and that's fine too.

**Comment by lgatto** [comment]
I have assigned this to myself, but @sje30, feel free to help out.

**Comment by sje30** [comment]
happy to help flesh out.

**Comment by sje30** [comment]
@rmflight -- see also this blog post https://thewinnower.com/papers/3674-the-selfish-scientist-s-guide-to-preprint-posting  

posting a preprint early maximises your chances for feedback, but also risk of being scooped.

**Comment by lgatto** [comment]
@sje30 I have created the box for us to get started. Feel free to go ahead and send a PR if you get some time.

**Comment by lgatto** [comment]
@sje30 Here's what I have so far:

> **Box 2** GitHub offers public of private repositories (the latter
> requiring a paid plans). Many projects decide to disseminate their
> work publicly and openly since the early stages of the projects to
> attract visibility and benefit from contributions from the community
> early on. Other projects will start as private repositories,
> limiting the collaboration among selected collaborators that are
> given access to the repository. These repositories can then be made
> public at a later stage, such as, for example, upon submission,
> acceptance, or publication of the work. I some cases, when the
> collaboration was exclusively meant to be private, some repositories
> might never be made publicly accessible. 

in https://github.com/lgatto/github-paper. Let's maybe address this in my fork before committing to the main repo.
