### ISSUE TITLE
Storing data with your code

### ISSUE THREAD

**Issue by sje30** [ypriverol/github-paper#112]
Many analyses require data files to run -- these can be stored in the repo if they are modest sized (up to a few MB), but you will hit problems with large data files.  Should this be mentioned?

**Comment by ypriverol** [comment]
@sje30 We have in rule one a dedicated box to this issue **Box 1** It explain the benefits and also LSF in summary.

**Comment by lgatto** [comment]
@sje30 does what we have cover what you meant, or can you think of something to add?

**Comment by sje30** [comment]
yes, thanks.
