### ISSUE TITLE
Example repos

### ISSUE THREAD

**Issue by sje30** [ypriverol/github-paper#113]
Your last table provides lots of nice examples of learning about github etc.  But what about some example real-world repos to show code from real projects across the spectrum of bioinformatics?  e.g. some with branches, PRs, etc showing all the goodness of github in action?

**Comment by ypriverol** [comment]
@sje30 we already included some from the authors. But feel free to recommend some of them. You can even add them and do a pull request.

**Comment by ypriverol** [comment]
@sje30 can you provide me a couple of suggestions of bioinformatics github repos. I don't want to be vias.

**Comment by peterjc** [comment]
We will all have biases, but the Galaxy Project's main repo would be a good example of a large and well known Bioinformatics project with an international team contributing (both funded and unfunded), and does a lot of good things like files for their code of conduct, contributing, uses continuous integration, etc https://github.com/galaxyproject/galaxy/

**Comment by sje30** [comment]
here's one of mine that is outside bioinf (I'd call it computational neuroscience, rather than comp bio):  https://github.com/sje30/waverepo

**Comment by lgatto** [comment]
@peterjc could you provide one galaxy reference to cite.

**Comment by lgatto** [comment]
See #120

**Comment by ypriverol** [comment]
Any good example for a bioinformatics lab repository.

**Comment by lgatto** [comment]
> Any good example for a bioinformatics lab repository.

I can't resist - there's https://github.com/ComputationalProteomicsUnit/, but the URL is so long.

**Comment by sje30** [comment]
also https://github.com/tgirke/tgirke.github.io

**Comment by ypriverol** [comment]
@lgatto Probably would be better to compile all the examples in the text in this table, even if we repeat them in both places. That means that readers can see them when they are reading the text (giving more context) and then in the table we summarize all the example including new ones (with the corresponding category).

**Comment by lgatto** [comment]
Reopening issue to keep track of this.

**Comment by ypriverol** [comment]
@lgatto agrre with the idea of put all examples from the manuscript in the table?

**Comment by lgatto** [comment]
yes

**Comment by peterjc** [comment]
@lgatto asked about how to cite Galaxy. In the absence of any papers specifically about the development model I would personally just cite Giardine *et al.* (2005) http://dx.doi.org/10.1101/gr.4086505 - but see https://wiki.galaxyproject.org/CitingGalaxy for more details.

**Comment by lgatto** [comment]
@ypriverol Now that we have all repos in a table, I would like to clean out that sentence in the text - at least remove the URLs, possibly rephrase. Will send a PR.

**Comment by lgatto** [comment]
I have pushed this change directly.
