### ISSUE TITLE
should mention be at least made of Gitlab and Bitbucket?

### ISSUE THREAD

**Issue by rmflight** [ypriverol/github-paper#115]
Both of these have similar features (not exactly same, but similar), and support unlimited private repos. And can host your own Gitlab for internal use. 

Might tie in with #111 ??

**Comment by lgatto** [comment]
These are mentioned in the first paragraph of the intro. Feel free to amend if you think it is not visible enough.

**Comment by rmflight** [comment]
Hmm, will have to look again when I get home, as obviously didn't remember.

**Comment by alex-konovalov** [comment]
GitLab also connects to #92 as one of possible exit strategies (but as far as I can see from #92, they are not discussed here).
