### ISSUE TITLE
Using templates for issues and pull requests

### ISSUE THREAD

**Issue by alex-konovalov** [ypriverol/github-paper#123]
https://github.com/blog/2111-issue-and-pull-request-templates explains how to make templates for issues and pull requests (we haven't yet implemented them in GAP, but I've submitted an issue at https://github.com/gap-system/gap/issues/645). 

A template could contain some reminders and checklists that could help to remind to add tests, document changes for the next release, check whether the branch for the PR is most appropriate etc. 

Do you think the paper could mention this feature as well? 

(There were some other recent UI changes on GitHub, like reactions and saved replies, but those likely may be omitted)

**Comment by ypriverol** [comment]
@alex-konovalov good point probably will be worst to mention this in the Supplemental Note with a detail explanation. What do you think @lgatto

**Comment by lgatto** [comment]
We have a mention of simplicity of issues in the main text. I was about to add a sentence that explained that it is also possible to create templates and point to the GtiHub documentation.

**Comment by alex-konovalov** [comment]
@lgatto yes, probably just saying something like "one could also establish templates for issues and pull requests containing further instructions and checklists (e.g. a reminder to report the version being used etc.)" and not more.

**Comment by ypriverol** [comment]
Done
