### ISSUE TITLE
most important git command is 'git help'

### ISSUE THREAD

**Issue by alex-konovalov** [ypriverol/github-paper#125]
Once I've got a very good advice from someone: the most important git command is
```
git help
```
and the next most important is 
```
git help -a
```
One should not rely on the network connection all the time to work with GitHub, and one can get the  documentation with `git help` even being offline. This may be worth to underline, to avoid false assumptions that going to GitHub is the only way to find help on Git.

I do not know if you think that this fits into the paper (and I had no time to read it carefully since I've discovered this project only today), so please forgive me if this is already explained somewhere or doesn't fit into the intended vision.

**Comment by lgatto** [comment]
I think we do emphasise that `git` works locally.  I have added  `git help [-a]` to the table 2. Thanks for your suggestion.
