### ISSUE TITLE
How many bioinformatics papers have used github?

### ISSUE THREAD

**Issue by sje30** [ypriverol/github-paper#129]
I can't resist the question in the subject line.  it would be great if you could estimate how many papers have supporting code bases on github.

Some caveats:
1. At this stage, you should probably focus on re-submitting the paper, rather than dealing with new queries like this!
2. given that github repos are not regarded as stable URLs for long-term storage, many papers probably used github but then stored stable version of code elsewhere, e.g. zenodo.

**Comment by sje30** [comment]
http://www.ncbi.nlm.nih.gov/pmc/?term=github  returns 4861 hits this morning...  that's pretty neat.

**Comment by lgatto** [comment]
I initially thought you mean actual papers written on github. If it is papers that have some code/analyses on github, I would have expected more; not sure how much, but more.

**Comment by sje30** [comment]
No, I didn't mean papers written on github.  I meant analysis on github that appeared in papers.  I have some more data to share...

**Comment by sje30** [comment]
I did a search on europepmc.org to find the occurrences of github.com in OA life-sciences papers.  The search query was 
   http://europepmc.org/search?query=github.com%20AND%20PUB_YEAR%3A2015

and varied the year in each case.  Here are the results showing the rise of github in the life-sciences:

year | count
-------| -------
2015 | 1819
2014 | 1077
2013 | 458
2012 | 162
2011 | 72
2010 | 23
2009 | 1
2008 | 0

The first paper was from Tom Blundell's group here in Cambridge (!):  http://europepmc.org/abstract/MED/19417059

and the github repo is still live: https://github.com/semin/ulla (with last update of Feb 4).  

CC: @semin

**Comment by sje30** [comment]
Perhaps there are more robust ways of finding github references on europepmc?

**Comment by lgatto** [comment]
That's very interesting!

**Comment by sje30** [comment]
Here's the R way of doing the count:

```
require(devtools)
install_github("njahn82/rebi")

require(rebi)


counts = function(year) {
  query = sprintf("github.com AND PUB_YEAR:%d", year)
  print(query)
  my_data <- epmc_search(query = query)
  my_data$hit_count
}

years = 2009:2015
sapply(years, counts)
```

**Comment by alex-konovalov** [comment]
FYI, "github bioinformatics" returns 10500 results on Google Scholar

**Comment by sje30** [comment]
`counts(2016)` already returns 499 hits.  Given the delay in getting papers onto PMC, 4*499 is likely to underestimate the counts for this year...

**Comment by sje30** [comment]
![github-usage](https://cloud.githubusercontent.com/assets/1095067/14174968/fb2a569c-f73f-11e5-849a-510ea5bd1c28.png)

**Comment by ypriverol** [comment]
should we add this to the paper. Would be important for new readers to now in numbers the actual impact  of github in bioinformatics?

**Comment by sje30** [comment]
1. note this is strictly all life-sciences papers, not just bioinformatics.

2. we could add extra data points to the graph showing mentions of other repos, e.g. sourceforge?  (What else is there?)

**Comment by ypriverol** [comment]
@sje30 life-sciences would be fine. I guess if we put googlecode and Bitbucket would be fine.

**Comment by sje30** [comment]
Not broken down by year:

```
sites = c("github.com", "bitbucket", "sourceforge", "googlecode")
sitehits = sapply(sites, function(s) epmc_search(query = s)$hit_count)
sitehits
github.com   bitbucket sourceforge  googlecode 
       4111          64         600           8 
```

**Comment by lgatto** [comment]
I think this would be a really nice blog post or a bit more work and a little paper of its own. I am not sure we could include it in the manuscript as is, and I find it too interesting to put up as as supplementary vignette, with only 1-2 sentences or a additional box. What do you think?

**Comment by sje30** [comment]
yes, I think we can pursue this elsewhere.  Submit your paper (see point 1 at top of issue!).  I do like the order-of-magnitude response:  https://scholar.google.co.uk/scholar?q=github+bioinformatics&btnG=&hl=en&as_sdt=0%2C5 returns 10,500 hits

**Comment by ypriverol** [comment]
@lgatto I guess we can even included it in the introduction.I don't think we have a limit for figures or restriction to put the the image in the introduction.

**Comment by alex-konovalov** [comment]
Another metric is that https://github.com/search?utf8=%E2%9C%93&q=bioinformatics repors 3206 repository results as of this moment.

**Comment by lgatto** [comment]
> I guess we can even included it in the introduction.I don't think we have a limit for figures or restriction to put the the image in the introduction. 

It's not a matter of word limits of figures. Reporting such data required to cross-ref different metrics and sources to be credible. So it would require more work that a few sentences or a paragraph in the intro would give credit for. But I agree that it is definitely an important point. 

May be we could just mention that there is an increase in using github and other similar repositories at reference this issue, or a dedicated repository that would collate all this, expand and, eventually write up - @sje30?

**Comment by ypriverol** [comment]
@lgatto a new manuscript would be to mush but probably would be enough by adding a folder to the repo with the charts and the scripts that provide the information. In the future we can incrementally provide more information about that. It would be something like:

..\
  \document
   ....
  \github-statistics

**Comment by lgatto** [comment]
> adding a folder to the repo with the charts and the scripts that provide the information

yes, of supplementary info, but it deserves better than supplementary info or a directory - it's own repo that we could link to would be nice. @sje30 [tweeted](https://twitter.com/StephenEglen/status/715508667060207617) about it. Let's see if others have tried it or have suggestions and how to proceed.

**Comment by sje30** [comment]
why don't I blog about it separately?  that would be easiest.  Its not a
major point, and I think google scholar count gives the right "feel" to
support the paper.

**Comment by ypriverol** [comment]
To be honest, if we explain the procedure that we do to retrieve the numbers and we agree about that. I would feel more than happy to include the image in the paper. Then we can go for more statistics and more strongly version.

**Comment by lgatto** [comment]
> why don't I blog about it separately?

If you have time, that's great - also add a repo for reproducibility and pull requests. We would have a sentence in the intro and link to your blog, where we could continue the discussion.

**Comment by sje30** [comment]
I'd like to do it in the next few days -- but when are you thinking of resubmitting?

**Comment by ypriverol** [comment]
yes, we should resubmit soon. To be honest I don't see why the current version is not accurate if we explain our query and provide the code in the repo.

**Comment by sje30** [comment]
if you have time to incorporate, then fine by me!

My only concern is that I noticed the following slighly issue:

```
epmc_search(query="github AND PUB_YEAR:2012")$hit_count
Retrieving page 1
Retrieving page 2
[1] 48
> epmc_search(query="github.com AND PUB_YEAR:2012")$hit_count
Retrieving page 1
Retrieving page 2
Retrieving page 3
Retrieving page 4
Retrieving page 5
Retrieving page 6
Retrieving page 7
[1] 162
```

so the more longer search term generates more hits.

My data was searching for github.com which I assume (but have not
verified) is the most appropriate.

**Comment by ypriverol** [comment]
- [ ] http://www.ncbi.nlm.nih.gov/pmc/?term=github    All (4862)
  - [ ] http://www.ncbi.nlm.nih.gov/pmc/?term=github.com All (31)

**Comment by alex-konovalov** [comment]
You may need to look at least for `github.io` as well, for software package that host website on GitHub pages and do not have their own domain. Could you check how many hits this will return?

Could it be also possible to produce some output (e.g. the line containing "github") so you will be able to see how relevant all these almost 5000K hits are?

**Comment by lgatto** [comment]
If I read these number correctly, querying ncbi  and epmc for github and github.com give opposite results. And there's github.io, as mentioned above. IMHO, this highlights the fact that these results ought to be reported and interpreted with care.

**Comment by ypriverol** [comment]
Probably you are rigth. Can we cite a blog post in Plos?

**Comment by sje30** [comment]
Yes.

For now I suggest you go with simple stat of 10.5k his on Google scholar...

On 31 March 2016 20:56:33 BST, Laurent Gatto <notifications@github.com> wrote:
>If I read these number correctly, querying ncbi  and epmc for github
>and github.com give opposite results. And there's github.io, as
>mentioned above. IMHO, this highlights the fact that these results
>ought to be reported and interpreted with care. 
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/ypriverol/github-paper/issues/129#issuecomment-204101541

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ypriverol** [comment]
Agree .. at the end we want to show is the trend by years to demonstrate and is getting common.

**Comment by Tobias-Ternent** [comment]
> why don't I blog about it separately?

Sounds like a great idea. I know this is a sight derailment form the original question, but since GitHub and Git itself are relatively new phenomena, perhaps a better historical usage of publicly accessible source version control in bioinformatics would be for SourceForge.
http://www.ncbi.nlm.nih.gov/pmc/?term=sourceforge
It might make for a nice graph to see the rise fall of SourceForge vs GitHub. Google Code perhaps would be nice too, but that seems a pain to try and search for.

**Comment by ypriverol** [comment]
http://www.ncbi.nlm.nih.gov/pmc/?term=sourceforge All (10213)

**Comment by alex-konovalov** [comment]
@sje30 yes, Google Scholar, even if it is not perfect in individual cases (it once reported to me my citation in a CV of my collaborator), reflects a general trend well. It also displays search context, and random checks show reasonable hits.

To compare, "github algebra" returned 4510 results, "github biochemistry" - 2450 and "github biostatistics" 1170.

**Comment by ypriverol** [comment]
@sje30 @lgatto as I promise I did a full study of bioinformatics repositories in Github 

(https://computationalproteomic.blogspot.com/b/post-preview?token=Kug82FMBAAA.voHykOOy-lpKQurF_zGP2wNmEXMbYgGuWcbIL4dppWx6_2p7oX87F6qPlJatdssKhVprMgH1Nx9ztSn8wEIHCw.eKvsXN5jqgYFCgQeNTepfQ&postId=7457344730221950208&type=POST)  

Interesting thing the chart generated by @sje30 using the data in PubMedCentral is almost identical that my plot (Figure 2) with the data coming from GitHub. I guess we have a really strong case now. Also I added more statistics around it.

**Comment by lgatto** [comment]
Not my view of strong case/statistics, sorry. 

Here's the data for google scholar (note how it returns results for pre-github years)

```r
gscholar <- structure(
c(46, 224, 812, 2240, 4860, 9310, 15300, 21600, 4280), 
.Names = c("2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016"), 
metadata = "searched from github.com on google scholar on Sat Apr  2 12:35:17 2016",
beforegh = structure(c(27, 19, 12, 14, 12), 
                     .Names = c("2007", "2006", "2005", "2004","2003")))
```

```r
plot(gscholar, xaxt = "n")
axis(1, at = 1:9, labels = 2008:2016
```
![gscholar](https://cloud.githubusercontent.com/assets/384198/14226182/73e3ee52-f8d2-11e5-9549-121fd9e41313.png)

The shape of the curve is pretty much the same as other sources, which points to a definite increase, although the actual values are uncertain. 

What are we trying to look at:
* Google trends - to get an idea of trendiness. 
* number of new relevant repositories (bioinformatics, computational biology, *omics) over time - shows an increase in adoption. 
* number of citations over time from different scholar sources - shows adoption and dissemination in the community. It would be great to compare repos the papers describe and citation of github repos.
* number of relevant repositories that are deleted: inform point 2, and info about preservation.

**Comment by ypriverol** [comment]
Probably is not an strong statistics/case. However we can demonstrate the following things:
   - We are trying to see the adoption of GitHub by numbers. The GitHub plot shows how many 
     repositories has been created from 2008 to 2016. This is an statistics coming from the same GitHub 
     then the number of  bioinformatics repo can be high because some developers do not use the  
     associated words but never less (in any case we explain how we did the search). 
   - Number of repositories by Language (also from GitHub) including forks, issues open etc. This will help 
     the user to compare with other reports from GitHub like http://githut.info/  
   - We leave the trend in the blog post and not include it inside the paper. But as you say it also can give   
     an idea of the trendiness.
   - Number of mentions in PubMed will give a check for what we guess from GitHub plot. I know that the 
     "real" numbers can be different because annotations differences. However, I don't think the trend will 
     be different.  
   - I'm not sure about how we can get the latest point. Deleted repos. 

What about leave this, as someone suggest in the blog post and cite it from the paper?

**Comment by sje30** [comment]
> What about leave this, as someone suggest in the blog post and cite it from the paper? 

My suggestion would be to keep things simple for now.  The reviewers
didn't ask for this (I did), so I think we should explore this
elsewhere...

**Comment by ypriverol** [comment]
@sje30 @lgatto Then probably would be enough to make the blog post public? for now and then we can explore as @sje30 said? I guess is a good idea to use this numbers in the introduction to make robust our title.

**Comment by ypriverol** [comment]
Hi all, I will make public the blog post and I just added a new label to the repo called follow up for future research including this issue.

**Comment by tompollard** [comment]
I thought it might be helpful to add a Jupyter Notebook containing code and plots for the analysis, so have submitted a pull request: https://github.com/ypriverol/github-paper/pull/205

The benefit of having the analysis in a Notebook is that:
- we can continue to refine the approach together
- including the notebook demonstrates another nice aspect of GitHub
