### ISSUE TITLE
Disclaimer

### ISSUE THREAD

**Issue by lgatto** [ypriverol/github-paper#13]
We need a disclaimer a conflict of interest note clarifying that we have no affiliation with GitHub and that they were not involved in this work.

**Comment by ypriverol** [comment]
@lgatto can you add that?

**Comment by lgatto** [comment]
Sure, will do.

**Comment by ypriverol** [comment]
@lgatto already added the disclaimer, can you do the merge and we can give one week of external contributions.

**Comment by lgatto** [comment]
Sorry, am in grant writing mode and could no follow the latest discussion. Will read you addition and merge, and follow up with the rest after submission.

**Comment by lgatto** [comment]
Just had a look at the disclaimer branch. That's not really what I meant and I don't really understand why we would want to add this. With disclaimer, I meant a statement explaining that we are not affiliated with github and that these views reflect our owns without any input from github.

**Comment by lgatto** [comment]
From the README file:
> ## Disclaimer
>
> The authors have no affiliation with [GitHub](https://github.com/), nor any commercial entity mentioned in this articel. The views described here reflect our owns without any input from any third party organisation.

Feel free to amend as you see fit.

**Comment by ypriverol** [comment]
Can you add your idea!!!

On Mon, Nov 23, 2015 at 9:26 PM, Laurent Gatto <notifications@github.com>
wrote:

> Just had a look at the disclaimer branch. That's not really what I meant
> and I don't really understand why we would want to add this. With
> disclaimer, I meant a statement explaining that we are not affiliated with
> github and that these views reflect our owns without any input from github.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ypriverol/github-paper/issues/13#issuecomment-159069553>
> .
>



-- 
Yasset Perez-Riverol PhD.
Bioinformatician
Proteomics Services Team, PRIDE Group
European Bioinformatics Institute (EMBL-EBI)
Wellcome Trust Genome Campus, Hinxton
Cambridge CB10 1SD, UK
Twitter: @ypriverol

**Comment by ypriverol** [comment]
Enviado de Samsung Mobile
