### ISSUE TITLE
Formulation of Rule 8

### ISSUE THREAD

**Issue by alex-konovalov** [ypriverol/github-paper#130]
As a consistency check, I've tried to see if it's obvious for me what does each of the rules mean if I will just read the list of rules without looking at the content of the sections, and whether a reader unfamiliar with GitHub could make sense of them. I think everything looks great, with the only exception (not github-related) in the Rule 8. What would you like to say by "and cite source code" ? 

Do you mean "and cite your source code yourself in the paper that you're writing", or do you want to suggest to be accurate in citing others work in the code (cf. [this recent blogpost](https://danielskatzblog.wordpress.com/2016/03/25/how-should-we-add-citations-inside-software/ ) by @danielskatz inspired by a discussion coming from a hackday at the Collaborations Workshop 2016)?

**Comment by ypriverol** [comment]
@alex-konovalov the intention is to promote that scientific manuscript also cite code by using the Zenodo DOI or other mechanisms. It will convert the source code of your project to a research "product" than can be easily cited an trace. Also it will promote the use of these citations independently of traditional publications associated with the software.

**Comment by alex-konovalov** [comment]
@ypriverol ok, so in other words, I understand this as you'd like to say that the authors should show examples of a good practice by citing their own code in their papers using the best possible way (which is with DOI). Thanks for clarification.

**Comment by ypriverol** [comment]
@alex-konovalov can you close the issue or do you want me to do some changes in the text.

**Comment by alex-konovalov** [comment]
I was trying to suggest better formulations, but neither "and cite own source code" nor "and cite (your) source code yourself" sound good, so in the absence of another ideas, I will just close it. 

And also, but saying "and cite source code" we are encouraging to properly cite source code written by anyone, what's absolutely right thing to do.

**Comment by danielskatz** [comment]
The language is a bit awkward (word order and choices often don't sound like American English) to me, but fully understandable as is.  For example, "Zenodo takes an archive" would be better to me as "Zenodo makes an archive" or "Zenodo creates an archive", and "providing openly" would be better for me as "openly providing".

**Comment by ypriverol** [comment]
@danielskatz would be great if you want to fork and make those changes. More than happy to accept then.

**Comment by danielskatz** [comment]
If you are not in a hurry, I can do this later today

**Comment by ypriverol** [comment]
please your more than welcome.

**Comment by danielskatz** [comment]
I note that PLOS-submission-eps-converted-to.pdf is needed to build but is not in the repo

**Comment by danielskatz** [comment]
I've submitted a pull request.

**Comment by ypriverol** [comment]
@lgatto @danielskatz Thanks . I normally do my updates in the md file. @lgatto are you controlling the sync between both files.

**Comment by lgatto** [comment]
Sorry, just catching up with this issue now, after seeing/commenting on the PR. I am happy to go through @danielskatz's PR and pull out individual changes later tonight or tomorrow.

**Comment by ypriverol** [comment]
@lgatto I can take this one and do a PR in the later today. Yo can define the final strategy for the charts @sje30 and how they would be included or referenced from the manuscript.
