### ISSUE TITLE
do not put derived files under version control

### ISSUE THREAD

**Issue by alex-konovalov** [ypriverol/github-paper#133]
(shortly before leaving the office) The title says is all - would you like to add this recommendation too?

**Comment by sje30** [comment]
agree with sentiment, but note that this repo includes a .pdf of the manuscript!

**Comment by lgatto** [comment]
Do not put derived files... that are easy to generate. In our case, the pdf is the file that gets submitted, so we want to keep a trace. 

I am not sure where to add it. It becomes technical and the right thing to do will depend, as in the pdf file here. May be this is mentioned in one of the references we cite.

**Comment by alex-konovalov** [comment]
@sje30 agree that there may be exceptions, like in the case when you want to store the submitted version of you may want to provide it for collaborators (I've tried to generate PDF yesterday to print and read at home and failed - cf #119). 

I had look at the text under rule 1. It says "All or parts of its content can be added explicitly to the list of files to track" go gives a hint that some files need not to be tracked, and later "Users usually track source code, text files, images and small data files inside their repos". Maybe just extend this text with "but usually do not track derived files such as build logs or compiled binaries"? The key word is *usually*, so if need be, exceptions could be made.

**Comment by lgatto** [comment]
Changed in PR #137
