### ISSUE TITLE
Add a citation to the repo

### ISSUE THREAD

**Issue by tompollard** [ypriverol/github-paper#140]
The paper suggests that:

> adding a CITATION file to the repository will inform your users how to cite and credit your project.

I expect the plan was to add this file when a full citation is available, but I'm just tracking the issue here as a reminder.

**Comment by ypriverol** [comment]
@tompollard we will added to the README if the paper is accepted.

**Comment by lgatto** [comment]
I have added a CITATION file with using the github URL. As mentioned by @ypriverol, we'll need to update it later - let's keep this issue open as a reminder.
