### ISSUE TITLE
Open source vs public

### ISSUE THREAD

**Issue by tompollard** [ypriverol/github-paper#141]
For me "open source" indicates the license associated with code, rather than whether or not a repository is public or private. Perhaps replace "Open source" with "Public" in the following sentence?

> Open source projects on GitHub are visible to everyone, but write permissions, i.e. the possibility to directly modify the content of a repo,

**Comment by prvst** [comment]
yes, that's correct. A repository can have the source code available, but that does not mean the project is "open source".

**Comment by tompollard** [comment]
Thanks, I'll be submitting a pull request shortly with some minor changes to the text, so will include a suggested change for this too.
