### ISSUE TITLE
Reference to support "pull requests improve code quality"

### ISSUE THREAD

**Issue by tompollard** [ypriverol/github-paper#142]
It would be good to add a reference to support the following statement, if possible:

> "Once a pull request is opened for review and discussion, it usually results in additional insights and increased code quality."

**Comment by ypriverol** [comment]
Couple of blog posts:
  - [ ] http://blog.smartlogic.io/2012/11/28/using-pull-requests-to-improve-code-quality-process-and-skills
  - Probably best option: Social Coding in GitHub: Transparency and Collaboration in an Open Software 
    Repository http://dl.acm.org/citation.cfm?id=2145396#citedby

**Comment by lgatto** [comment]
@ypriverol could send that paper, I can't access it from home.

**Comment by ypriverol** [comment]
https://www.cs.cmu.edu/~xia/resources/Documents/cscw2012_Github-paper-FinalVersion-1.pdf
[cscw2012_Github-paper-FinalVersion-1.pdf](https://github.com/ypriverol/github-paper/files/198373/cscw2012_Github-paper-FinalVersion-1.pdf)
