### ISSUE TITLE
Mentioning Figshare alongside Zenodo

### ISSUE THREAD

**Issue by tompollard** [ypriverol/github-paper#143]
The following paragraph discusses the ability to archive code and obtain a DOI via Zenodo:

> GitHub now enables the use of DOIs to cite the code deposited, using the data archiving tool Zenodo (https://zenodo.org/). The procedure is simple (see https://guides.github.com/activities/citable-code/) and, by default, Zenodo takes an archive of a repository each time a new release is created in GitHub.

My understanding is that Figshare offer a similar service, so perhaps they should be mentioned too? See the following links for example:
- https://mozillascience.github.io/code-research-object/
- https://figshare.com/blog/Working_with_Github_and_Mozilla_to_enable_Code_as_a_Research_Output_/117

**Comment by lgatto** [comment]
I think it is good to add FigShare, indeed. Could you send a PR?

**Comment by tompollard** [comment]
Sure, will do!

**Comment by ypriverol** [comment]
@tompollard I guess we can close this issue.

**Comment by tompollard** [comment]
Yes, that's fine. Might suggest a minor update if anyone responds to:  https://twitter.com/tompollard/status/715621938861883394
