### ISSUE TITLE
Integrate repo with Travis

### ISSUE THREAD

**Issue by tompollard** [ypriverol/github-paper#145]
To emphasise the following point, it would be good if this repo was integrated with Travis to check that changes to markdown, style files etc don't break the Pandoc builds:

> Travis CI builds and tests the source code using a plethora of
options such as different platforms and interpreter versions
(Supplementary Note, Section 2). In addition, it offers notifications
which allow your team and contributors to know if the new changes
work, and prevent the introduction of errors in the code (for instance
when merging pull requests), making the repo always ready to
use. 

I should be able to copy across most of the setup from https://github.com/tompollard/phd_thesis_markdown, so will submit a pull request shortly.

**Comment by ypriverol** [comment]
Great Idea

**Comment by lgatto** [comment]
This would be nice, but I wouldn't necessarily want to actually generate a new pdf at each commit. I think we should keep the pdfs as a submission snapshot.

**Comment by tompollard** [comment]
This wouldn't affect content in the repository.  We would just trigger a test build on Travis whenever a new commit is made to check whether the commit has broken anything. 

This is most useful when reviewing pull requests because you can immediately see whether or not the requested change will break the build.

**Comment by sje30** [comment]
That sounds neat.  I think people reading the article will expect to see elements of the ten tips used in this repo!

**Comment by alex-konovalov** [comment]
:100: great idea. Just to check, Travis will only run `pandoc manuscript.md -o manuscript.tex` but will not generate the PDF file, so if someone want to work on #119, these two issues are independent, right?

**Comment by tompollard** [comment]
thanks @alex-konovalov, that's right. At the moment Travis only runs the first step of the build process ("make manuscript.tex"). We need to fix #119 before the other steps can be tested too.

**Comment by alex-konovalov** [comment]
thanks @tompollard - my comment and your PR were submitted same minute :)

**Comment by lgatto** [comment]
Great contribution @tompollard, thanks!
