### ISSUE TITLE
Outline process for adding DOIs to Europe PMC

### ISSUE THREAD

**Issue by tompollard** [ypriverol/github-paper#148]
It is interesting to see that dataset DOIs can be added directly to Europe PMC:

> Once the DOI has been assigned, you can add it to literature information resources such
as Europe PubMed Central \cite{EuropePMCConsortium:2015}.

The citation to http://dx.doi.org/10.1093/nar/gku1061 is useful but I can't see any clear guidance for adding data DOIs. Is it possible to outline the process in the article?

**Comment by ypriverol** [comment]
Probably is our of our scope.

**Comment by tompollard** [comment]
Yes, I wondered that - no problem if you'd like to close this issue.
