### ISSUE TITLE
Using services like Github helps to backup code

### ISSUE THREAD

**Issue by tompollard** [ypriverol/github-paper#151]
Perhaps I put too much trust in it, but for me a major benefit of Github (and distributed version control in general) is that it helps to make sure there is always a backup. I feel like this should be highlighted somewhere, perhaps even as a top level rule.

**Comment by lgatto** [comment]
May be not a rule, but probably worth mentioning that backup is a side effect of using GitHub or similar resources.

**Comment by ypriverol** [comment]
Probably would be nice to mention it in the introduction. I will prefer to do not deviate the main attention around the aim of git and github.

**Comment by alex-konovalov** [comment]
@tompollard good idea! Even more, with distributed VCS, not only you have backup elsewhere and can experiment with your fork/clone, but also you can easily experiment with git creating "toy" repositories. I remember that helped me greatly to learn Mercurial a while time ago, not like in times of using CVS and SVN with the centrally hosted repository... Just in case this may be useful to reflect in a couple of words.

**Comment by lgatto** [comment]
See PR #156
