### ISSUE TITLE
Asking for comments and external contributions

### ISSUE THREAD

**Issue by lgatto** [ypriverol/github-paper#16]
> I would like to open the article for suggestions before it publication, can we twit and ask for recommendations before the publication. What do you think? - @ypriverol 

Excellent idea. Could we postpone this a bit until we sort out the last details?

**Comment by ypriverol** [comment]
@lgatto @timosachsenberg more than happy to make the current version available for comments!!!

**Comment by timosachsenberg** [comment]
maybe after we added the disclaimer?

**Comment by ypriverol** [comment]
Do you have an example of a disclaimer?

**Comment by ypriverol** [comment]
@lgatto we are ready to get some external feedback

**Comment by lgatto** [comment]
Ok
