### ISSUE TITLE
Rendering of Jupyter Notebooks

### ISSUE THREAD

**Issue by tompollard** [ypriverol/github-paper#173]
GitHub renders Jupyter Notebooks, which is useful for people seeking to share reproducible research workflows. This might be worth mentioning somewhere:  http://blog.jupyter.org/2015/05/07/rendering-notebooks-on-github/

**Comment by lgatto** [comment]
I think that becomes a bit too technical.

**Comment by tompollard** [comment]
Sounds like others are in agreement, so I'll close this issue.
