### ISSUE TITLE
licensing

### ISSUE THREAD

**Issue by danielskatz** [ypriverol/github-paper#177]
I don't think we really talk about licensing enough.  The text in 8 is ok, but it might be better to say something like:

You should use an OSI approved license (https://opensource.org/licenses/alphabetical). Common licenses such as those listed on http://choosealicense.com are preferred. Note that the LICENSE file in the repository should be a plain-text file containing the contents of an OSI approved license, not just a reference to the license.

**Comment by lgatto** [comment]
Good suggestion, I'll update accordingly.

What do you mean by *included in the repository* at the end of the first sentence - that it should be part of the repo?

**Comment by danielskatz** [comment]
I think the text got a bit messed up when I wrote the issue - I later edited it, as it is now:

You should use an OSI approved license (https://opensource.org/licenses/alphabetical). Common licenses such as those listed on http://choosealicense.com are preferred. Note that the LICENSE file in the repository should be a plain-text file containing the contents of an OSI approved license, not just a reference to the license.

**Comment by lgatto** [comment]
Thanks, updated in PR #178
