### ISSUE TITLE
Combining tables on one page

### ISSUE THREAD

**Issue by alex-konovalov** [ypriverol/github-paper#182]
Tables look much better now, but each of them occupies a single page. It seems from the availability of the free space that it may be possible to fit them into one page.

**Comment by alex-konovalov** [comment]
Also, URLs in the tables are not clickable.

**Comment by lgatto** [comment]
Clickable URLs is a thing I am happy to do later. 

However, I am not sure how much time we should waste with figuring out how  to format the tables, as they will do it again themselves; I might try to split cells over a two lines.

**Comment by alex-konovalov** [comment]
While we are on tables: is the order of items in table supposed to be alphabetical or there is some other logic what's recommended first?

**Comment by lgatto** [comment]
> While we are on tables: is the order of items in table supposed to be alphabetical or there is some other logic what's recommended first?

I haven't identified any logic and meant to put some, but forgot. Feel free to do it if you want.

**Comment by alex-konovalov** [comment]
I suggest alphabetically - will reorder them.

**Comment by tompollard** [comment]
The table width issue should be solvable by changing the markdown used to generate them, I think. If some of the rows wrapped onto multiple lines, then the width will be okay. I'll take a look shortly.

**Comment by lgatto** [comment]
@alex-konovalov I am updating the URLs, will also reorder table 1.

**Comment by lgatto** [comment]
I have shortened the tables by removing the type in table 2 (it was not terribly informative and did not relate to anything directly in the text) and shorted the URLs be remove the common prefix in table 1, as suggested by @alex-konovalov  (with actual full/working clickable links).

It would be possible to fix the with of the columns, but that would require editing at the latex level as it can't be done at the markdown level. Let's just leave is like this for now.
