### ISSUE TITLE
Remarks on Rule 1

### ISSUE THREAD

**Issue by alex-konovalov** [ypriverol/github-paper#185]
1) The 2nd sentence "Every change, from fixing a typo to a complete redesign of the software, is tracked and controlled by a unique identifier." seems to be out of place and should be moved later. Also, what does "controlled" mean here? 

2) "Following Tony Rossini's advice in 2005 to "commit early, commit often..." - do we have a citation? Also, the word _commit_ should be introduced before. This could be done around the new place found for the sentence from (1), perhaps above the example showing the use of `git commit`.

3) Do we need to say that one can create repositories in any order - first locally, then push to github, of first on github, then locally? I've met situations when this was a real question.

**Comment by lgatto** [comment]
> "Following Tony Rossini's advice in 2005 to "commit early, commit often..." - do we have a citation? 

See https://github.com/ypriverol/github-paper/issues/101

**Comment by lgatto** [comment]
> 3) Do we need to say that one can create repositories in any order - first locally, then push to github, of first on github, then locally? I've met situations when this was a real question.

That could be a useful addition, indeed.

**Comment by alex-konovalov** [comment]
@lgatto will add it after merging #192 then.

**Comment by alex-konovalov** [comment]
@lgatto hm, I am struggling with finding a good formulation of this. We said that "In addition to local copies of the repository, it is straightforward to create remote repositories on GitHub (called `origin`, with default branch `master` - see below) using the web interface, and then synchronize local and remote repositories." so synchronization already implies that. If I am trying to insert the phrase about the order of creation, then it makes synchronization looking like one-time action rather then ongoing activity. I will try to formulate it better, or just leave the text as is.

**Comment by lgatto** [comment]
May be it is clear enough the way it is now. No need to force it, I think.

**Comment by lgatto** [comment]
Re your first point, I'll replace by 
> Every change, from fixing a typo to a complete redesign of the software, is tracked and uniquely identified.
