### ISSUE TITLE
Example for Rule 3

### ISSUE THREAD

**Issue by alex-konovalov** [ypriverol/github-paper#187]
It says: "It allows anyone to develop and test novel features with existing code and offers the possibility of contributing novel features, bug fixes, and improvements to documentation (https://twitter.com/rgfitzjohn/status/708309767240982528)"

It may be better to remove the link to the twitter and find an example of the project which has a label for documentation-related pull request to add in the table 1 (like we use [here](https://github.com/gap-system/gap/pulls?q=is%3Apr+label%3Adocumentation+is%3Aclosed))

**Comment by lgatto** [comment]
Fine by me.

**Comment by lgatto** [comment]
The reason I put up this tweet was not so much to give an example (we would need to give one for each case, really), but to show that even simple contributions are appreciated.

**Comment by lgatto** [comment]
I'll remove the link to the tweet.
