### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by ypriverol** [ypriverol/github-paper#2]
@javizca @lgatto @ruiwanguk I will way for the first iteration, new ideas before add any other idea. @timosachsenberg I already add your contribution to Rule 1 and 2.

**Comment by timosachsenberg** [comment]
did you see that I updated the PR with contributions to the other rules?

**Comment by ypriverol** [comment]
I was in the merge? PR?

**Comment by timosachsenberg** [comment]
yep

**Comment by ypriverol** [comment]
I accpted all the changes in the merge and only remove some minor things in the introduction.
