### ISSUE TITLE
rule 3: paragraph 2 still reads a bit clumsy

### ISSUE THREAD

**Issue by kblin** [ypriverol/github-paper#203]
The beginning of the second paragraph of rule 2 is still a bit complicated. Maybe changing

> Concurrent development -- that is, users making commits in parallel to the same repository
> -- can be organised using different approaches. The most common way ...

to 

> Many contributors can work on the same repository at the same time without running into edit conflicts. There are multiple strategies for this, and the most common way...

will help a bit.

(Edited to actually complete my sentence)

**Comment by lgatto** [comment]
I think the 'without running into edit conflicts' is actually a bit misleading; there won't be conflicts while editing, there certainly can be conflicts when merging. What do you think?

**Comment by kblin** [comment]
Right, but this is as opposed to having a .doc file on Dropbox, where you already run into conflicts while editing. I still think this is less confusing than "concurrent development"
