### ISSUE TITLE
Ready to submit

### ISSUE THREAD

**Issue by ypriverol** [ypriverol/github-paper#21]
@lgatto @Leprevost @julianu @timosachsenberg Ready for the last review and submit. Please give me a +1

**Comment by Leprevost** [comment]
+1

**Comment by timosachsenberg** [comment]
its still missing some information like affiliations of all authors, grants etc.

**Comment by ypriverol** [comment]
Please can you add this information, I will do it in my case.

**Comment by julianu** [comment]
added the affiliation.
please accept the changes of Felipe to give it a final read

**Comment by ypriverol** [comment]
Thanks for adding this details.
