### ISSUE TITLE
Retitle rules 2, 3, 4 in imperative voice

### ISSUE THREAD

**Issue by jshoyer** [ypriverol/github-paper#218]
Currently your rules 2, 3, 4 are not actual concise advice ("rules"), they are just general headings. 'Ten simple rules' articles frequently have this problem.

Cf. the seven simple rules at the end of this piece by Eckhardt: http://www.cs.cmu.edu/~davide/howto/git_lose.html

**Comment by tompollard** [comment]
I agree, this would be an improvement. If the submission is accepted, perhaps we can update the rules during proofing...
