### ISSUE TITLE
found typo in abstract

### ISSUE THREAD

**Issue by rmflight** [ypriverol/github-paper#221]
I can't find the abstract in the repo, but just noticed on the preprint (and assuming this is in the submitted version as well)

> issues and continuous integration and automation using, for example, Travis CI and **codevoc**

I've bolded it here, **codevoc** should be **codecov**

Did anyone catch that in the proofs?

**Comment by lgatto** [comment]
Abstract is biorxiv only (there is no abstract for 10 simple rule manuscripts). Thanks for the catch. Will fix now.
