### ISSUE TITLE
Table 2 is incorrect in the PLOS version of the article

### ISSUE THREAD

**Issue by mandel01** [ypriverol/github-paper#226]
It just repeats Table 1. I see it is correct in the repo here.

![2016-07-15-07-27-06-screenshot](https://cloud.githubusercontent.com/assets/8669125/16874189/8e334370-4a5d-11e6-8ee8-f8beaf6fbde8.png)

**Comment by ypriverol** [comment]
I guess the editorial process (that was painful) make a mistake. I will try to be in contact with Plos Computational Biology.
