### ISSUE TITLE
Article comments on PLOS

### ISSUE THREAD

**Issue by prvst** [ypriverol/github-paper#229]
@ypriverol , @javizca 

We have [comments](http://journals.plos.org/ploscompbiol/article/comments?id=10.1371/journal.pcbi.1004947) on the article web page, specially about PLOS mistakes.

**Comment by lgatto** [comment]
>We have
>[comments](http://journals.plos.org/ploscompbiol/article/comments?id=10.1371/journal.pcbi.1004947)
>on the article web page, specially about PLOS mistakes.

We should redirect readers to the pre-print, if PLoS can't sort their shit a bit faster.
