### ISSUE TITLE
Format for submission and refs

### ISSUE THREAD

**Issue by lgatto** [ypriverol/github-paper#26]
What format are you going to submit? 

Re references, you can use a bibtex file, the in the text, cite using `[@label]` and compile, with references with 
```
pandoc manuscript.md -o manuscript.pdf -N --bibliography=bibliography.bib --csl=bibstyle.csl
```
adapting `bibstyle.csl` to the style needed.

**Comment by ypriverol** [comment]
@laurent for the journal we will convert the current version to doc file and we will make available this version also, the problem is that submission also needs doc files.

**Comment by lgatto** [comment]
Submission needs doc file? That depends very much were you want to submit.

**Comment by ypriverol** [comment]
Plos One?

**Comment by javizca** [comment]
I told Yasset already. If the manuscript is too long over 2500 words (those are the guidelines for this type of manuscript) it will need to be shortened before submission.

**Comment by lgatto** [comment]
PLoS have a LaTeX template.

**Comment by ypriverol** [comment]
We will try, if is to complex we will convert to pdf the final version.

**Comment by lgatto** [comment]
So we need a hefty cut down, as we are currently at about 3100 words.

**Comment by ypriverol** [comment]
Something important @javizca if we remove some words to match the Journal guidelines, the final version should be approved here. Perhaps is better before the final submission if we do this cut using the same strategy based on pull requests.

**Comment by lgatto** [comment]
I agree with @ypriverol - don't get started with fiddling and emailing a doc file. Honestly, given the content of this paper, that would be ridiculous.

**Comment by ypriverol** [comment]
@lgatto we will do our best ;) but sure tomorrow @javizca and my self will work to remove some content and we will make clear the changes to be approve. BTW @lgatto can you help me adding the references using bitex and Latex. It would be great if you can add also some format, I can try to look for the Plos in Computational Biology template for Latex.

**Comment by lgatto** [comment]
Have you sent a submission enquiry to PLoS Comp Biol?

**Comment by javizca** [comment]
Yes, it was done quite a few months ago.

**Comment by lgatto** [comment]
Ok then, conversion to PLoS template should be easy from `md` to `tex` then using the sty provided by the journal. Let's do this once the version is close to final.

**Comment by ypriverol** [comment]
@laurent Here the latex template from Plos http://journals.plos.org/ploscompbiol/s/file?id=SyJ3/plos-latex-template.zip

**Comment by ypriverol** [comment]
@lgatto you can merge the latest pull request and them add Plos style and the references after that, we will provide that latest changes open a new full request for the final approval and we will submit. Agree ?

**Comment by lgatto** [comment]
No, that's not how it works. PLoS provides a LaTeX template, not markdown AFAIK. Let's do this conversion after the massive cut-down.

**Comment by ypriverol** [comment]
ok

**Comment by ypriverol** [comment]
@lgatto ready, all major changes are included can you add the template?

**Comment by lgatto** [comment]
I'm busy at a conference and teaching until Thursday. Will get a go after that.

**Comment by lgatto** [comment]
@javizca I currently count about 2870 words. More cutting down or conversion to LaTeX and pdf?

**Comment by javizca** [comment]
Let's try it this way. If they complain, we can always cut it down later. Quite often these limits are not strict, they are just guidelines.

**Comment by javizca** [comment]
As I mentioned, the figure legend needs still to be added. But I am not even sure everyone was happy with the current version of the figure. I will seen a separate e-mail about this in the next 5 min.

**Comment by lgatto** [comment]
There is a legend:

>  The structure of a GitHub-based project illustrating the projects structure and the interactions with the community.

**Comment by javizca** [comment]
Is this more correct? Otherwise, perfectly fine for me.

The structure of a GitHub-based project illustrating the projects' structure and the interactions with the community.

OR

The structure of a GitHub-based project illustrating the structure of projects and the interactions with the community.

**Comment by lgatto** [comment]
If you mean projects and interactions in general (i.e more than 1), I think it should be 

> The structure of a GitHub-based project illustrating projects' structure and interactions with the community. 

or even 

> The structure of a GitHub-based project illustrating project structure and interactions with the community. 

If only one in particular (which I think is not appropriate here)

> The structure of a GitHub-based project illustrating the project's structure and the interactions with the community.

**Comment by julianu** [comment]
+1 on "The structure of a GitHub-based project illustrating project structure and interactions with the community."

**Comment by javizca** [comment]
BTW, the figure does not need to be included in the manuscript file. I have just checked it.

And Acknowledgements to financial sources must not be included there either, so please delete that part. They must be provided in the manuscript submission system. I will do it there.

**Comment by javizca** [comment]
About the legend, what about ...? (they are a bit less redundant)
"Overall framework of GitHub-based projects illustrating their structure and interactions with the community".

or just

"Overall structure of GitHub-based projects".

**Comment by lgatto** [comment]
> Overall structure of GitHub-based projects.

is very vague. 

> Overall framework of GitHub-based projects illustrating their structure and interactions with the community.

Why framework?

**Comment by javizca** [comment]
It is fine for me whatever you think is best.

**Comment by fu** [comment]
maybe something like "Overall structure and workflow of GitHub-based projects maintaining stable releases while interacting with the community". 

Another point, if fig 1 is in color we could use the actual colors for the "build passing" shield from Travis. Makes it easier to recognize.

**Comment by lgatto** [comment]
> BTW, the figure does not need to be included in the manuscript file. I have just checked it.

Yes, indeed.

> And Acknowledgements to financial sources must not be included there either, so please delete that part. They must be provided in the manuscript submission system. I will do it there.

@javizca I'm not sure about that one. Acknowledgements might need to be added in the submission system, but I think they should still come in the manuscript - that what I did for my recent submission and there is an Acknowledgement in the template.

**Comment by lgatto** [comment]
@javizca the PLoS pdf and LaTeX are on github now. Let me know if you need anything.

**Comment by lgatto** [comment]
@javizca there are also instructions in the `README.md` file documenting the conversion.

**Comment by javizca** [comment]
@lgatto When we submitted this manuscript last year (http://www.ncbi.nlm.nih.gov/pubmed/?term=25033262), I was explicitly asked to remove the acknowledgements to the financial sources afterwards. I had to repeat the submission.

**Comment by lgatto** [comment]
@javizca Interesting, I submitted on the 7th October with acknowledgements,  and haven't had any complains. Well, if manuscript submission was an effective process, I suppose we would know by now...

**Comment by lgatto** [comment]
Closing, as the format and refs issue is solved.
