### ISSUE TITLE
reference clarification

### ISSUE THREAD

**Issue by lgatto** [ypriverol/github-paper#32]
What is this reference:

> Comment: Fowler, Martin, and Matthew Foemmel. "Continuous integration." Thought-Works http://www.thoughtworks.com/Continuous Integration. pdf (2006)

Is it 
- this book [Continuous Integration: Improving Software Quality and Reducing Risk](http://www.amazon.com/gp/product/0321336380)
- this [web page](https://www.thoughtworks.com/continuous-integration) 
- a comment on a web page?

**Comment by ypriverol** [comment]
This is a web page

**Comment by lgatto** [comment]
which one?

**Comment by ypriverol** [comment]
We can replace by the book Continuous Integration: Improving Software Quality and Reducing Risk

**Comment by lgatto** [comment]
But that does not make sense any more with your text

> In 2005, Martin Fowler defined the basic principles for continuous integration in software development [ref]

What is this 2006 reference by Fowler et al.?

**Comment by ypriverol** [comment]
The article is this https://scholar.google.co.uk/scholar?hl=en&q=Continuous+integration.%22+Thoughtworks&btnG=&as_sdt=1%2C5&as_sdtp=

**Comment by lgatto** [comment]
C'mon, what's that supposed to be

![2015-12-09-234216_725x342_scrot](https://cloud.githubusercontent.com/assets/384198/11702513/27319f4e-9ecf-11e5-8090-657cd918e192.png)

This reference does not relate to anything

```
@misc{fowler2006continuous,
  title={Continuous Integration. ThoughtWorks},
  author={Fowler, Martin},
  year={2006}
}
```
Is it possibly this [page](http://www.martinfowler.com/articles/continuousIntegration.html)?

**Comment by ypriverol** [comment]
https://scholar.google.co.uk/scholar?q=Continuous+integration+Fowler&btnG=&hl=en&as_sdt=0%2C5 Agree with the reference.
