### ISSUE TITLE
Using you/your or one

### ISSUE THREAD

**Issue by lgatto** [ypriverol/github-paper#34]
The text addresses a reader directly with the _you_/_your_ form. This sounds rather casual - is this a conscious decision? Would the more formal use of _one_ be more appropriate?

**Comment by ypriverol** [comment]
Please @lgatto use the one that you consider more appropriate, we were discussing here this topic, because also the Ten simple rules manuscript is also kind of casual/informal manuscript. But I will accept your proposal.

**Comment by lgatto** [comment]
> the Ten simple rules manuscript is also kind of casual/informal manuscript

Which is why I'm asking - I will check in previous examples and follow what has been done.

**Comment by ypriverol** [comment]
I think you/you is fine. Here some examples

>if you are making a figure for yourself (http://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1003833)

> what functionality do you require, (http://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1003506)

**Comment by javizca** [comment]
I tried to make it a bit more homogeneous in this respect, but it is still not "perfect". The rules are written in a very informal way, but maybe the "yous" could still be replaced more by "the user". But these manuscripts are quite informal so, maybe it can be kept this way. I can do a final read before submission and take the decision there.

**Comment by ypriverol** [comment]
@javizca  and @lgatto  I was reading a couple of examples and all of them use you/your because it is the idea to make close the manuscript to the users. See examples:

> if you are making a figure for yourself (http://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1003833)

> what functionality do you require, (http://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1003506)

Then I think we are find if we use the same style.

**Comment by lgatto** [comment]
Ok, leaving the informal you/your then.
