### ISSUE TITLE
Clarification

### ISSUE THREAD

**Issue by lgatto** [ypriverol/github-paper#35]
What do the numbers in 

> weekly discussion **9/5-9/16** related with datasets

mean?

**Comment by ypriverol** [comment]
@lgatto this is a suggestion from @timosachsenberg about how to call issues and milestones.

**Comment by lgatto** [comment]
If this is not clarified, it should be removed. Re-opening to remind myself to amend accordingly.

**Comment by lgatto** [comment]
Close me only once PR #38 is merged.
