### ISSUE TITLE
Adding tag upon submission 

### ISSUE THREAD

**Issue by lgatto** [ypriverol/github-paper#46]
@javizca once you have submitted, could you tag all the files in the repo as `v1.0`, please (or let me know and I'll do it). Thanks.

**Comment by javizca** [comment]
Do we need the figure legend in the main manuscript? I am not sure actually, after reading the instructions to authors. I usually put them there, but it seems it may not be mandatory. We have only one figure anyway. 
I can submit it like that and wait till it goes under review.
In any case, I think we should wait till that for version 1.0.

**Comment by lgatto** [comment]
Can't push tags to this repo. Whoever has these rights, please do the following:
```
git tag -a -m"first submission" v1.0
git push --tags 
```

**Comment by julianu** [comment]
done
