### ISSUE TITLE
incorrectly refer to bootstrap as platform

### ISSUE THREAD

**Issue by rmflight** [ypriverol/github-paper#48]
In **Rule 9**, "bootstrap" is referred to as a platform

> can be integrated with other platforms such as Bootstrap

I think this is incorrect, as from my understanding Bootstrap is rather a framework that provides CSS and javascript that makes it easy to generate really nice websites that scale well across different screens. Disqus, in contrast is a platform, as it is hosted elsewhere and provides a central platform for commenting.

**Comment by lgatto** [comment]
Thanks @rmflight for your suggestion. I'll keep the issue open so that we can address this in the next round of updates.
