### ISSUE TITLE
A Quick Introduction to Version Control with Git and GitHub

### ISSUE THREAD

**Issue by lgatto** [ypriverol/github-paper#49]
[A Quick Introduction to Version Control with Git and GitHub](http://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1004668) was just published. We should definitely cite it.

**Comment by ypriverol** [comment]
+1

**Comment by lgatto** [comment]
Another one that we missed, pointed out by Titus

> [Git can facilitate greater reproducibility and increased transparency in science](http://scfbm.biomedcentral.com/articles/10.1186/1751-0473-8-7), Karthik Ram.
