### ISSUE TITLE
Review Comments - First Iteration. 

### ISSUE THREAD

**Issue by ypriverol** [ypriverol/github-paper#50]
@lgatto @julianu @ruiwanguk @javizca @Leprevost @timosachsenberg Hi all of you. We have already the feedback from the reviewers. I suggest to create issues with each comment and then we can address, comment and close them. Please give me a +1 if you are Agree. I can split all of them.

**Comment by Leprevost** [comment]
+1

**Comment by lgatto** [comment]
You are asking me to agree/disagree with something I have not seen/read. Please create a `REVIEW.md` file with the editors email, containing the reviews, so that we can read the feedback.

**Comment by timosachsenberg** [comment]
+1

----- Original Message -----

**Comment by lgatto** [comment]
Just got the email from Juan. I can create the REVIEW file.

**Comment by ypriverol** [comment]
@lgatto Juan just sent an email with the reviewer comments, that is the reason why I propose this

**Comment by julianu** [comment]
+1

**Comment by ypriverol** [comment]
@lgatto do you think is a bad idea to split all comments in issues or do you think we should work on this using the REVIEW.md document. The idea with the issues is that we can trace better the new changes and improvements.

**Comment by lgatto** [comment]
Reviers 2 and 3 comments can be addressed by open/amend/close issues (so +1 for these), but what Titus suggest, and I am inclined to agree with him requires more thoughts.  Do we want to address 2 and 3 first, and think about 1 afterwards, or other way?

**Comment by lgatto** [comment]
> do you think is a bad idea to split all comments in issues or do you think we should work on this using the REVIEW.md document. The idea with the issues is that we can trace better the new changes and improvements.

A bit of both.

**Comment by ypriverol** [comment]
I will argue yes, The idea is to split and summarized the simple things to address first in some issues (cluster some comments that are related). Especially as you said the comments from 2 and 3.

**Comment by lgatto** [comment]
Ok then, let's go for reviewer 2 and 3 points with separate issues, then we proceed with more substantial refactoring.

**Comment by ypriverol** [comment]
Ok. I will start to create the issues (cluster comments and point to the especific part of the REVIEWS File).

**Comment by ypriverol** [comment]
Hi all do you think it would be interesting to add the reviewers to this interaction, at the end we know them and we have their account (at least for the public reviewers)

**Comment by Leprevost** [comment]
hum, I think that we could at least extend the invitation to them, that would become a very interesting example of a open peer-review process =)

**Comment by lgatto** [comment]
> Hi all do you think it would be interesting to add the reviewers to this interaction, at the end we know them and we have their account (at least for the public reviewers)

See [this](https://twitter.com/ctitusbrown/status/697092242142416896) tweet

![2016-02-09-203059_611x294_scrot](https://cloud.githubusercontent.com/assets/384198/12929815/baf7abb0-cf6c-11e5-9cbc-806ac8e84263.png)

Let's do our job first, then request more feedback from the community and reviewers, if they wish.

**Comment by ypriverol** [comment]
@lgatto the last pull-request before going to Titus comments is done. When anybody take a look and accept the changes, then we can invite the open reviewers (Titus) to take a look to the version.
