### ISSUE TITLE
Title should be refined

### ISSUE THREAD

**Issue by ypriverol** [ypriverol/github-paper#52]
## Reviewer 3:

> Small thing: I would suggest a minor title change to reflect that (even though this is going into PLOS CompBio) that the rules aren't just specific to bioinformatics. In fact, the term 'bioinformatics' appears exactly exactly twice in the paper (leaving out the title and affiliations), both times in the 'Introduction' text! Beyond that, one could substitute any discipline for 'bioinformatics' as long as it required some need for version control. Maybe something like "Ten Simple Rules for Taking Advantage of GitHub for Scientists". I'm horrible with titles, though, maybe I shouldn't come up with this :)

**Comment by ypriverol** [comment]
@all We have to options here or replace the word 

    1- 'bioinformatics' by Scientist

 or open even more the scope and remove the last word: 

    2 - Ten Simple Rules for Taking Advantages of GitHub

option **3** is keep the title and justiied why

What do you think?

**Comment by julianu** [comment]
Actually I would prefer the second option. Though I do not now, whether this broadens the expectations to wide. But then, it will be published in PLOS Comp Biol and not some pure computer science journal, so the scope should be clear.

**Comment by ypriverol** [comment]
I also like the option 2 because it solve the problem highlighted by the reviewer and also as @julianu said, it opens the scope to a more broadly audience.

**Comment by lgatto** [comment]
I like option 2 too.

**Comment by ypriverol** [comment]
@timosachsenberg @Leprevost @javizca @flu ?

**Comment by javizca** [comment]
option 2 is fine

**Comment by timosachsenberg** [comment]
option 2 is fine: is it really "Taking Advantages of" or should it be "Taking Advantage of"?

**Comment by ypriverol** [comment]
@timosachsenberg good one. Let me ask to an english speaker. @tobias-ternet can you let us know what is the best way: 

> "Taking Advantages of" or should it be "Taking Advantage of"

**Comment by Tobias-Ternent** [comment]
You rang?
"Taking Advantage" would be best, because that means the following 10 rules will lead to success with GitHub.
"Taking Advantage**s**" instead isn't technically correct here- that would be best used instead if you were talking about how GitHub has benefits over something else for users.

I like this 2nd title in general, reminds me of the US sitcom entitled "8 simple rules (for dating my teenage daughter".

**Comment by ypriverol** [comment]
Thanks @tobias-ternent for the clarification.

**Comment by ypriverol** [comment]
I change the title to the 2 option if some one is not happy we can always open the issue again.
