### ISSUE TITLE
Introduction Refinements

### ISSUE THREAD

**Issue by ypriverol** [ypriverol/github-paper#53]
# Reviewer 2:

> Reproducibility should not be mentioned (in the introduction) as a motivating factor. Having available software is of course a necessary condition, but in reality the temporal scale (years after the original analysis) and complexity (operating systems, compilers, libraries, software ecosystem, ...) of analyses really mean that the individual investigator interested in reproducible research MUST take charge of the situation at the time of the original analysis, and cannot rely on availability of versioned software after the fact.

> It would be very helpful to call out, with links to repository locations, exemplar github repositories of individual developers (from among the authors?), labs (from the authors, or from successful projects / groups like bedtools, Lior Pachter's lab?), intermediate projects (hts / samtools?), and larger projects (rOpenSci??) that effectively use GitHub.

# Reviewer 3:

> Pg. 1, Introduction, para1: "Here, we introduce the main features of GitHub, a popular web-based 14 platform which offers a free and integrated environment for hosting the source code, documentation and web page for open source projects."

>Probably a better way to word ‘web page’, something like ‘public project-related web content’ since many projects are more complex.

>Pg. 2, Introduction, para 2: small revision suggestion

>“These rules have been ordered to reflect a typical development process: learning git and GitHub basics, use of branches, labeling and tagging of code snapshots, tracking project bugs and enhancements using issues, etc”

**Comment by ypriverol** [comment]
Reproducibility in the document is not mentioned as long-term reproducibility. Instead is more like the code/program/algorithms should be available like the data. I don't want to change the sentence because the idea is clear.

**Comment by lgatto** [comment]
> It would be very helpful to call out, with links to repository locations, exemplar github repositories of individual developers (from among the authors?), labs (from the authors, or from successful projects / groups like bedtools, Lior Pachter's lab?), intermediate projects (hts / samtools?), and larger projects (rOpenSci??) that effectively use GitHub.

That's a very good point, and I will provide some of my repos/orgs. We should also put this repo somewhere in the text.

**Comment by lgatto** [comment]
> Reproducibility in the document is not mentioned as long-term reproducibility. 

May be we should talk about [replicability, rather than reproducibility](http://lgatto.github.io/rr-what-should-be-our-goals/). But I think we need to highlight primarily traceability and flexibility. 

> Instead is more like the code/program/algorithms should be available like the data. I don't want to change the sentence because the idea is clear. 

There is more to it than availability - see above. I would even claim that availability is only a positive side effect of public code versioning. Git/GitHub are also terribly useful for private projects.

May be we can change/clarify the sentence to avoid confusion.

**Comment by ypriverol** [comment]
I was actually thinking in the correct word for that and really like replicability. Can you update the sentence. I like your idea.

**Comment by timosachsenberg** [comment]
if we want we can also add OpenMS. Its a good example for  a larger (in the top 10% in team size according to OpenHub).

**Comment by ypriverol** [comment]
Perfect, really like the idea, please add it.

**Comment by ypriverol** [comment]
Just added the examples of repositories in the current version.

**Comment by ypriverol** [comment]
@lgatto do you have a reference we can use for replicability, traceability?

**Comment by lgatto** [comment]
I can do that now, but keep an issue for that specific point and I will get back to it asap.
