### ISSUE TITLE
Small change in Rule 3 about branching goal

### ISSUE THREAD

**Issue by ypriverol** [ypriverol/github-paper#56]
# Reviewer 2:

> Rule 3 should be refined to emphasize that branches are really short-term departures from master; it is too easy for academic developers to lose track of the thrust of their project, or for individuals to work in isolation for extended periods, so that their contribution cannot easily be merged back to master.

**Comment by lgatto** [comment]
> One of the easiest ways to make a mess for yourself with Git ...

First, I don't think this is a very elegant way to expressing ourselves, but, more importantly, it is completely non-understandable to anyone that hasn't used git/GitHub before. I suggest the following 

> When developing different features in parallel, there is a risk to apply incompatible changes in different branches/forks; these are said to become out of sync.

**Comment by lgatto** [comment]
I also suggest the following:

> If you pull frequently, you will keep your copy of the repo up to date, and you will have the opportunity to merge your changed code with others' contributors **without requiring to manually address conflicts to bring the branches in sync again**.

**Comment by lgatto** [comment]
Last suggestion for this rule - title could be

> Developing and collaborating on new features: branching and forking

Jus *Use branches* is not very useful for those that don't already know git/GitHub.
