### ISSUE TITLE
Github or Git should be removed from the title of the Rules

### ISSUE THREAD

**Issue by ypriverol** [ypriverol/github-paper#58]
# Reviewer 2:

>Of course the emphasis on GitHub is challenging. We know that this service cannot be indefinite, just as Sourceforge, Google Code, etc., have all faded. The manuscript should emphasize principles as much as possible, rather than the GitHub realization of those principles; I realize that GitHub does a great job of bringing bioinformatics developers into the modern age. Minimally, I think that Git and GitHub should be removed from the title and all 'Rules' headers.

**Comment by ypriverol** [comment]
Hi all ,I removed from rule 7 but I think is important in rule 2.

**Comment by lgatto** [comment]
> I removed from rule 7

Do you mean in the title only?

**Comment by ypriverol** [comment]
Yes @lgatto in the title, I just created a pull-request with the changes.
