### ISSUE TITLE
Automation - what tasks?

### ISSUE THREAD

**Issue by lgatto** [ypriverol/github-paper#75]
> We suggest that all these three tasks become part of your project.

What tasks? I don't think they are explicitly defined in the texts. I have removed that sentence, and also 

> It also shows that is currently working and has documentation that reflects the current code.

which was incomplete and undefined. 

Are the tasks (1) running code to check syntax, (2) testing and (3) generating documentation?

**Comment by lgatto** [comment]
On a related note, that I will address in a later issue, I am wondering if rule 5 and 6 (automation, continuous integration) shouldn't be merged. For instance rule 5 is *The code must always be ready to use: continuously integrate* but CI is mentioned in rule 6. This change would also lead to make the 3 tasks above more explicit.

**Comment by ypriverol** [comment]
@lgatto I was to merge them because it is also related with one of the reviewer comments https://github.com/ypriverol/github-paper/issues/55 . I agree with the merge. However, any simple mathematical operation in the rules will break the title. If we merge or split rules will not be any more Ten simple rules.

**Comment by lgatto** [comment]
That's not a good reason to keep them separate, to be honest. But as I said, I will get back to this later, as I think I agree with Titus that the overall article is very technical and not useful to beginners. I am thinking of starting with a simpler rule 1.

**Comment by ypriverol** [comment]
@lgatto Agree that is not a good reason. I only highlighted the issue in the title to keep that in mind. Also, agree to start with a simple rule that give a quick introduction or first contact of users with the article. I already create a Supplementary information that can be use to move technical discussions to it.

**Comment by lgatto** [comment]
See PR #79
