### ISSUE TITLE
Mention git LFS somewhere 

### ISSUE THREAD

**Issue by lgatto** [ypriverol/github-paper#81]
I am temporarily removing this from the main text, as it sits a bit in the middle of nowhere

> Note that until recently, GitHub was lacking support for storing large files (>100 MB), a issue that has been recently addressed by the GitHub large file storage (Supplementary Note, section 1). 

I will of course add it back, possibly under a new rule, that discusses what to track: text-based files vs binary data, large/small data, ...

**Comment by ypriverol** [comment]
@lgatto This is a great idea because it is related with one of the reviewer comments about the GitHub large file storage.

**Comment by ypriverol** [comment]
@lgatto the current pull-request contains a possible solution which is a Suplemental Note https://github.com/ypriverol/github-paper/pull/86 we can extend the current Supplemental Note explaining how to track: text-based files vs binary data, large/small data, ...

**Comment by lgatto** [comment]
I think it would be better to have this in the main paper as a *box*; things get so easily lost in supplementary information, and I think this is important information, especially for new users, that could make their first versioning experience a success or a failure.

**Comment by ypriverol** [comment]
ok.. feel free to move the current version of the Supplemental Note to a box.

**Comment by ypriverol** [comment]
@laurent the current version of the manuscript contains the proper text in rule 1 (see #86) . I remove the content from the Suppl to the main text. Please feel free to give the style that you want or refine it.
