### ISSUE TITLE
RFC: New Rule

### ISSUE THREAD

**Issue by lgatto** [ypriverol/github-paper#83]
Rules 5 (CI) and 6 (automation) where somehow redundant - the former defined the concepts and the latter explained how to implement this on GitHub. I have tried to rationalise this and combine them into a rule *Let GitHub do some tasks for you: integrate and automate*. Please comment here if you think this should be reverted. 

This leaves room for a new rule. In issue #81, the LFS paragraph was not really fitting anywhere, so it might be used for a new rule about organising a repo. Somehow, we don't explain that having a repo is not a substitute for project management, nor what type of files (binary, text, size) are good candidates for versioning. 

Any comments, suggestions?

**Comment by ypriverol** [comment]
@lgatto I guess the problem of suggesting different structures s (in my opinion) like going into details and can be vias by our experience. We can focus the rule in the file types supported by github web, the LFS and probably give a couple of links about project management.

**Comment by lgatto** [comment]
Ok, may be not a rule as such, but a box with additional tips. I think these are useful for people new to versioning and scientists (as opposed to programmers) - to be honest, the first version was not terribly helpful to newcomers. I will write this section as a additional note to rule 1.

**Comment by ypriverol** [comment]
Agree!!

**Comment by ypriverol** [comment]
@laurent I moved again from Suppl information to main text the LSF part and summarise the complete section in one paragraph including a batch example to commit the files. Please take a look and let me know.

**Comment by lgatto** [comment]
As the project management/LFS was not made a rule, we are missing one. So I split the integration/automation again in two, as was in the previous version. See PR #88
