### ISSUE TITLE
Names of the Rules following the Reviewer 1 suggestions

### ISSUE THREAD

**Issue by ypriverol** [ypriverol/github-paper#85]
Reviewer 1 suggested to rename the rules like:

>Rule 1: Use GitHub to track your lab and personal proejcts.
Rule N: Use GitHub to deliver and maintain versions of your code.
Rule N: Use GitHub to advertise your project. (can include web site)
rule N: Use GitHub to track issues reported by users.
Rule N: GitHub integrated services can do lots of nice things (CI).

Please let me know if you are agree. I would prefer to leave the name of Github for the things that are Github specific and keep the names for the more generic things. Please let me know your opinion.

**Comment by lgatto** [comment]
I have already changed some rules along these lines. I think having rules with simple and direct messages like that it good, and don't mind if GitHub appears. Please don't change everything quite yet, let's do this at the very end.

**Comment by ypriverol** [comment]
Agree @lgatto I'm just saying that we should say clear in the respond to the reviewers that we changed the content and focus of each rule but not the titles. Just in those cases that make sense. My point is that we need to respond to the reviewers then I want to be clear and write the respond in to REVIEWER.md

**Comment by lgatto** [comment]
Here is what we have for now (in PR)

```
## Rule 1. Use GitHub to track your projects
## Rule 2. GitHub for single users, teams and organisations
## Rule 3. Developing and collaborating on new features: branching and forking
## Rule 4. Naming branches and commits: tags and semantic versions
## Rule 5: Let GitHub do some tasks for you: integrate
## Rule 6: Let GitHub do more tasks for you: automate 
## Rule 7. Use GitHub to openly and collaboratively discuss, address and close issues
## Rule 8. Make your code easily citable, and cite source code!
## Rule 9. Promote and discuss your projects: web page and more
## Rule 10. Use GitHub to be social: follow and watch
```

I think we name GitHub where they provide the main feature, and don't when it's (mainly) a git feature. Anyway, they are more snappy now, I think.
