### ISSUE TITLE
Final call for comments from authors 

### ISSUE THREAD

**Issue by lgatto** [ypriverol/github-paper#89]
Dear all - could you all have a read at the latest version and check that we have addressed the reviewers' comments by tomorrow evening. We can then have another round of public comments and then re-submit. Thanks in advance.

**Comment by ypriverol** [comment]
@laurent perfect!!! I will try to move forward this with each author.

**Comment by javizca** [comment]
I will have a thorough look at the beginning of next week. I have too many things to do right now. But we still have 2 weeks to resubmit based on the 60 days we were given. So, it will be fine.

**Comment by lgatto** [comment]
No worries, @javizca. Will request contributions from the community tonight, so you might even want to wait a bit.

**Comment by prvst** [comment]
+1

**Comment by tompollard** [comment]
@lgatto, is there still time to submit contributions?

**Comment by lgatto** [comment]
Hoping to finalise soon, but probably not before the beginning of the weekend, so feel free to contribute.

**Comment by lgatto** [comment]
I have updated the README page and closed the pubic PR request period. I think there are only a few minor updates left. @javizca - what's the time line for resubmission?

**Comment by javizca** [comment]
Next Friday, one week to go

**Comment by lgatto** [comment]
Ok, thanks. The funding info, which is needed during submission, is in [funding.md](https://github.com/ypriverol/github-paper/blob/master/document/funding.md).
