### ISSUE TITLE
Risk related to the commercial nature of GitHub 

### ISSUE THREAD

**Issue by lgatto** [ypriverol/github-paper#92]
Reviewer 2 highlighted the risks related to commercial products: 

> Of course the emphasis on GitHub is challenging. We know that this service cannot be indefinite, just as Sourceforge, Google Code, etc., have all faded.

This is a very pertinent point, which is why it is good to highlight it here, in a dedicated issue. In our reply, we specify:

> More generally, corporate support is a double edge sword: companies
> often produce clean products and support, but users are at the mercy
> of financially motivated decision. On the good side, thanks to the
> distributed nature of git, users would not loose their repositories
> nor the commit history. Issues could be downloaded using the GitHub
> API, but the nice interface would be lost. **This is a risk that some
> might not take, and certainly a discussion worth having**, albeit not
> in the manuscript.

**Comment by tompollard** [comment]
Fading is inevitable regardless of the funding model, so I'm not clear why the commercial aspect of Github would be a problem in itself. It is difficult to think of a digital service that can be indefinite, whether commercial or not.
