### ISSUE TITLE
No .gitignore file

### ISSUE THREAD

**Issue by peterjc** [ypriverol/github-paper#94]
The main ``README.md`` says to use ``make clean`` to avoid checking in anything other than changes to ``manuscript-plot.tex`` and ``manuscript-plos.pdf`` but I would suggest adding all the LaTeX intermediate files to a ``.gitignore`` file. e.g.

```
#Ignore LaTeX temp files
*.aux
*.log
*.out
*.toc
*.haux
*.htoc
```

This probably falls under "Rule 2. Learn Git and embrace its power" although also maybe "Rule 6: Automate for better code quality" (here automate for cleaner commits) ;)

**Comment by lgatto** [comment]
Thank @peterjc - have added a `.gitignore` file with your suggestion.
