### ISSUE TITLE
Rule 3, paragraph 2 doesn't read right

### ISSUE THREAD

**Issue by rmflight** [ypriverol/github-paper#97]
This sentence in paragraph 2 of rule 3 reads odd

>During such a development, the original branch might continuously be developed and other features might be merged into the master branch.

It is unclear what exactly is meant here, and may need to have a concrete example rather than just this sentence.

**Comment by ypriverol** [comment]
@rmflight we remove the sentence because it was redundant. take a look to the current version and close te issue if you are agree.

**Comment by rmflight** [comment]
This looks much better!
